### ISSUE TITLE
How to integrate typeahead with this package

### ISSUE THREAD

**Issue by rahuldagli** [yogiben/meteor-autoform-tags#9]
I've included comerc:autoform-typeahead  package. However, its giving an error:

```
Exception from Tracker afterFlush function:
TypeError: e.$input.typeahead is not a function
```

Code 

```
  tags:
    optional:true
    type: String
    autoform:
        type: 'tags'
        afFieldInput:
            typeahead:
                source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']
                freeInput: true
```
